index:
    path: /
    controller: App\Controller\HomeController::index

Othello:
  path: /othello
  controller: App\Controller\OthelloController::index

othelloInit:
  path: /othello/init
  controller: App\Controller\OthelloController::othelloInit

othelloMove:
  path: /othello/move
  controller: App\Controller\OthelloController::othelloMove